# Site settings
title: Arnab K. Majee
email: amajee@unm.edu
description: > # this means to ignore newlines until "baseurl:"
  Postdoctoral Fellow at The University of New Mexico. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arnabmajee.github.io" # the base hostname & protocol for your site
production_url: "https://arnabmajee.github.io"
github_username: arnabmajee
permalink: /blog/:year/:month/:title.html

#twitter:
#  username: 

sass:
  style: compressed

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
